# Generated by Django 2.2 on 2019-05-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Reasom',
            new_name='Reason',
        ),
    ]
