# Generated by Django 2.2 on 2019-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_activitye_intereste_skille'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activitye',
        ),
        migrations.DeleteModel(
            name='Skille',
        ),
        migrations.AddField(
            model_name='intereste',
            name='Activity',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intereste',
            name='Skill',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
    ]
